%YAML:1.0
---
# 保存选项
# -- 保存在彩色图像上画出读入的全部匹配和RANSAC后inliers的结果
save_match: 1
# -- 保存对齐后未裁剪的结果
save_align: 1
# -- 保存对齐且裁剪后的结果
save_crop: 1
# -- 保存把模板图像有效区域变换到测试图像产生的候选包围盒坐标,该测试图像中所有候选包围盒画在图像上的结果(用于与后续步骤对接,请勿修改)
# save_box: 1
# 结果目录
# -- 保存在彩色图像上画出读入的全部匹配和RANSAC后inliers的结果
res_match_dir: "./result/match"
# -- 保存对齐后未裁剪的结果
res_align_dir: "./result/align"
# -- 保存对齐且裁剪后的结果
res_crop_dir: "./result/crop"
# -- 保存把模板图像有效区域变换到测试图像产生的候选包围盒坐标,该测试图像中所有候选包围盒画在图像上的结果
res_box_dir: "./result/box"
# 测试图像相关
# -- 测试图像目录,其中测试图像扩展名为.jpg
test_im_dir: "/media/bjm/Data/datasets/vobile_project/shelf/milk/test/layer/img"
# -- 测试图像名列表文件,其中每一行是一幅测试图像名,无扩展名
test_name_file: "/media/bjm/Data/datasets/vobile_project/shelf/milk/test/layer/img_names.txt"
# -- 测试图像recurrent pattern特征匹配结果目录
test_rp_match_dir: "/media/bjm/Data/datasets/vobile_project/shelf/milk/test/layer/match_list"
# 模板图像相关
# -- 模板图像目录,其中模板图像扩展名为.jpg
tmpl_im_dir: "/media/bjm/Data/datasets/vobile_project/shelf/milk/test/template/img"
# -- 模板图像名列表文件,其中每一行是一幅模板图像名,无扩展名
tmpl_name_file: "/media/bjm/Data/datasets/vobile_project/shelf/milk/test/template/img_names.txt"
# -- 模板图像有效区域坐标目录,其中每个模板图像一个txt文件,文件中只有一行,依次为xmin,xmax,ymin,ymax,用空格分隔
tmpl_valid_dir: "/media/bjm/Data/datasets/vobile_project/shelf/milk/test/template/valid_region_coords"
